# permissions for end users to view cronicleevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronicle-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronicleevent-viewer-role
rules:
- apiGroups:
  - cronicle.net
  resources:
  - cronicleevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cronicle.net
  resources:
  - cronicleevents/status
  verbs:
  - get
