---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cronicle.net
  resources:
  - cronicleevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronicle.net
  resources:
  - cronicleevents/finalizers
  verbs:
  - update
- apiGroups:
  - cronicle.net
  resources:
  - cronicleevents/status
  verbs:
  - get
  - patch
  - update
