apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronicle-operator-services
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronicle-operator-services-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronicle-operator-services
subjects:
- kind: ServiceAccount
  name: cronicle-operator-controller-manager
  namespace: cronicle-operator-system
