apiVersion: cronicle.net/v1
kind: CronicleEvent
metadata:
  labels:
    app.kubernetes.io/name: cronicle-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronicleevent-sample
spec:
  # TODO(user): Add fields here
