apiVersion: cronicle.net/v1
kind: CronicleEvent
metadata:
  labels:
    app.kubernetes.io/name: cronicle-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronicleevent-sample
spec:
  enabled: 1
  category: "general"
  title: "Cronicle Operator"
  target: "glxn8vg3i0m"
  timing:
    days: [1, 2, 3, 4 ,5]
    hours: [0, 6, 12, 18]
    minutes: [5, 10, 15, 20]
  params:
    script: "sleep 100"
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name