apiVersion: cronicle.net/v1
kind: CronicleEvent
metadata:
  labels:
    app.kubernetes.io/name: cronicle-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronicleevent-sample
spec:
  enabled: 0
  catchUp: 1
  notes: "Created by operator"
  plugin: "shellplug"
  category: "general"
  title: "Product Import"
  target: "gly2y8x3r02"
  detached: 1
  timing:
    minutes: [0,5,10,15,20,25,30,35,40,45,50,55]
  params:
    script: |
      #!/bin/bash
      echo "Hello World"
    annotate: 1
    json: 1
  instanceSelector:
    matchLabels:
      app.kubernetes.io/instance: cronicle-master