apiVersion: cronicle.net/v1
kind: CronicleEvent
metadata:
  labels:
    app.kubernetes.io/name: cronicle-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronicleevent-sample
spec:
  enabled: 1
  category: "genaral"
  title: "Test go operator"
  target: "6712b650ec8b"
  params:
    script: "echo 'Hello, World!'"

